name: Android - push - feature
on:
  commit:
    branches:
      - 'feature/*'

jobs:
  unit_test:
    build:
      runs-on: ubuntu-latest

      steps:

        - name: Change wrapper permissions
          run: chmod +x ./gradlew

        - name: Run Tests
          run: ./gradlew test